version: '1.0'

networks:
  node-api-network:
    name: "node-api-network"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql_server
    networks:
      - node-api-network
  
  mysql_server:
    image: mysql
    networks:
      - node-api-network